#! /bin/sh

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap          11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

bspc rule -a Thunar state=pseudo_tiled
bspc rule -a Gvim state=pseudo_tiled
bspc rule -a URxvt:python state=pseudo_tiled
bspc rule -a Pavucontrol state=pseudo_tiled
bspc rule -a qBittorrent desktop='^1' follow=on
bspc rule -a Gimp desktop='^1' follow=on state=floating
bspc rule -a google-chrome-stable desktop='^2' follow=on
bspc rule -a URxvt:ncmpcpp desktop='^3' follow=on state=pseudo_tiled
bspc config external_rules_command "/home/lite/.config/bspwm/spotify"
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on
urxvt -name scratchpad -e ~/bin/scratch &
blueman-applet &

bspc config presel_feedback_color "$color7"
bspc config normal_border_color "$color8"
bspc config focused_border_color "$color7"
bspc config active_border_color "$color7"

$HOME/.config/polybar/launch.sh
