#! /bin/sh

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d         

bspc config border_width         1
bspc config window_gap           22

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

bspc rule -a URxvt:python state=floating
bspc rule -a Thunar state=pseudo_tiled
bspc rule -a Gvim state=pseudo_tiled
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^2' state=pseudo_tiled
bspc rule -a URxvt:ncmpcpp desktop='^3' follow=on state=pseudo_tiled
bspc config external_rules_command "/home/couch/.config/bspwm/spotify"
bspc rule -a Pavucontrol desktop='^3' follow=on state=pseudo_tiled
bspc rule -a Gimp desktop='^4' follow=on state=floating
bspc rule -a qemu desktop='^5'
bspc rule -a URxvt:weechat desktop='^6' follow=on state=pseudo_tiled
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on
urxvt -name scratchpad -e ~/bin/scratch &

bspc config presel_feedback_color "$color7"
bspc config normal_border_color "$color8"
bspc config focused_border_color "$color7"
bspc config active_border_color "$color7"

panel &
