#! /bin/sh

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

num_mon=$(bspc query -M | wc -l)

nowplaying() {
    mpc current
}

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="%{F$color15} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$color1} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$color15
								;;
							M*)
								# focused monitor
								FG=#color15
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$color8
								;;
							F*)
								# focused free desktop
								FG=#color15
								;;
							o*)
								# occupied desktop
								FG=$color5
								;;
							O*)
								# focused occupied desktop
								FG=#color15
								;;
							u*)
								# urgent desktop
								FG=$color1
								;;
							U*)
								# focused urgent desktop
								FG=#color15
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					#[LTG]*)
						# layout, state and flags
					#	wm="${wm}%{F$color2} ${name} %{B-}%{F-}"
					#	;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}%{c} %{F$color15}$(nowplaying)%{r}${sys}"
done
